### ISSUE TITLE
Hill Chart

### ISSUE THREAD

**Issue by ALEXOTANO** [basecamp/handbook#103]
Basecamp is amazing! Our team started to use it, both design and dev teams!

We want to share the hill chart with our client so the client could see the progress, is there a way to do that? shared link / API / webhook / whatever works if we can actually get the hill chart somehow. 

Thank you guys! Amazing job!

**Comment by rosa** [comment]
Hey Alex! So happy to hear you're enjoying Basecamp so far. I'm afraid we currently don't support sharing the hill chart with clients via our client feature so they can follow the progress. No support via the API or webhooks either 😬 I'll bring this up internally since it sounds like something desirable in many cases, and it's something we could certainly allow in the future. It's not straightforward to implement right now, since you can individually choose which lists the client can see, and these lists might not correspond to the lists tracked in the hill chart, but it's certainly something we could think on how to do and possibly come up with some solution. 

Thanks again for your kind words!

**Comment by michalradacz** [comment]
Hi. This thread was closed, but no relevant answer or solution given by developers. Hmmmm, can you implement this anyway or can you add button Save as image for example as alternative to sharing? It may be verry usefull.

**Comment by jhubert** [comment]
@jeremy Would love to have this functionality as we work with clients and showing them progress on the shared goals. Any update here?
