### ISSUE TITLE
Links to internal resources

### ISSUE THREAD

**Issue by lexsys27** [basecamp/handbook#28]
First of all, thank you for sharing your handbook to the general public! It is very interesting to learn other companies culture. And it is typically very hard to do..

Reading this handbook I have seen a lot of links that either go to the private GitHub repos or to Basecamp projects. [Example01](https://github.com/basecamp/handbook/blob/master/our-rituals.md#meetups) and [Example02](https://github.com/basecamp/handbook/blob/master/our-internal-systems.md#shipshape).

It would be nice to remove that links and substitute them with description what that system/resource provides if it is appropriate.

**Comment by jeremy** [comment]
Generally speaking, private links are often appropriate and to be expected since we're referencing out to auxiliary/additional info. These aren't links that are stand-ins for content that _should_ be in the handbook. They're all "dive deeper."

Example 1: This links to staff sharing their personal tips about preparing for, attending, and returning from meetups. This has been distilled in the handbook already. The link is to see individual staff sharing their thoughts.

Example 2: Shipshape is a "low touch," unintrusive security auditor for macOS. It's implemented as a [Bats](https://github.com/sstephenson/bats) test suite and it pushes test results to a git repos. Failing tests mention the user, causing GitHub to alert them. This was built to be open source, so that'll (eventually) fix the private link 😊

Happy to address other cases you've hit, too! Thanks @lexsys27.
