### ISSUE TITLE
Please update the links related to ../basecamp/shipshape

### ISSUE THREAD

**Issue by spritle** [basecamp/handbook#29]
https://github.com/basecamp/handbook/blob/master/getting-started.md#your-buddy

**Comment by alarowe** [comment]
Generally speaking, private links are often appropriate and to be expected since we're referencing out to auxiliary/additional info. These aren't links that are stand-ins for content that should be in the handbook. They're all "dive deeper."

Shipshape is a "low touch," unintrusive security auditor for macOS. It's implemented as a Bats test suite and it pushes test results to a git repos. Failing tests mention the user, causing GitHub to alert them. This was built to be open source, so that'll (eventually) fix the private link 😊

**Comment by spritle** [comment]
👍

**Comment by ollywhitespace** [comment]
Would also be interesting in learning more about ShipShape - do you have any ideas when you might be Open Sourcing it?
