### ISSUE TITLE
Clarify differences between levels?

### ISSUE THREAD

**Issue by Moeser** [basecamp/handbook#31]
In making-a-career.md:
> Day to day, though, these titles aren't really much of a factor. 

Can you expand on that?  Aren't the day to day tasks for a Junior going to be significantly different than those of a Principal?  How do you define the differences between each level?  Do you take scope of work/influence into account?

**Comment by jeremy** [comment]
These levels are how we recognize *mastery* of a role rather than differences between roles. We don't separate "junior" and "senior" work. Day to day, these titles aren't indicators of the kind or "level" of work you're doing, so they… aren't really much of a factor. They help us track career progression, celebrate together, and orient newcomers.
